### ISSUE TITLE
Claim Rewards wont work anymore

### ISSUE THREAD

**Issue by jkroepke** [Dance-Dog/RewardClaim#7]
Hi,

i'm using the rewardclaim 0.1.1 version.

If I click on a card inside a lobby, nothing happens, but this error will be appear:

```
[13:46:02] [Thread-310/WARN] [rewardclaim]: Failed to claim reward. Server sent back a 403 status code. Received the following body:
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Error</title><script src="/cdn-cgi/apps/head/rsjQeg9CKMkfLDB8kU7GG-F1JRE.js"></script></head><body><pre>ForbiddenError: invalid csrf token<br> &nbsp; &nbsp;at csrf (/primary/delivery-rewards/node_modules/csurf/index.js:112:19)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/primary/delivery-rewards/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/primary/delivery-rewards/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at /primary/delivery-rewards/node_modules/express-rate-limit/lib/express-rate-limit.js:121:7<br> &nbsp; &nbsp;at MemoryStore.incr (/primary/delivery-rewards/node_modules/express-rate-limit/lib/memory-store.js:20:5)<br> &nbsp; &nbsp;at rateLimit (/primary/delivery-rewards/node_modules/express-rate-limit/lib/express-rate-limit.js:66:19)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/primary/delivery-rewards/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/primary/delivery-rewards/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/primary/delivery-rewards/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/primary/delivery-rewards/node_modules/express/lib/router/layer.js:95:5)</pre><script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"67033a3a38d5c290","token":"f3771f7e976f42e9a8e7ac5210bdeaa5","version":"2021.6.0","si":10}'></script></body></html>
```

**Comment by najoan125** [comment]
ForbiddenError: invalid csrf token
    at csrf (/primary/delivery-rewards/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/primary/delivery-rewards/node_modules/express/lib/router/layer.js:95:5)
    at next (/primary/delivery-rewards/node_modules/express/lib/router/route.js:137:13)
    at /primary/delivery-rewards/node_modules/express-rate-limit/lib/express-rate-limit.js:121:7
    at MemoryStore.incr (/primary/delivery-rewards/node_modules/express-rate-limit/lib/memory-store.js:20:5)
    at rateLimit (/primary/delivery-rewards/node_modules/express-rate-limit/lib/express-rate-limit.js:66:19)
    at Layer.handle [as handle_request] (/primary/delivery-rewards/node_modules/express/lib/router/layer.js:95:5)
    at next (/primary/delivery-rewards/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/primary/delivery-rewards/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/primary/delivery-rewards/node_modules/express/lib/router/layer.js:95:5)

**Comment by jkroepke** [comment]
this could work https://github.com/PyICoder/RewardClaim/releases/tag/v0.2

**Comment by js6pak** [comment]
*I love how there are [3](https://github.com/PyICoder/RewardClaim) [different](https://github.com/xcfrg/rewardclaim) [forks](https://github.com/js6pak/rewardclaim) doing the same thing*

**Comment by jkroepke** [comment]
2 of the 3 forks are not relevant, because they dont provide prebuilt artifacts.

**Comment by js6pak** [comment]
All of them do tho, 1 with releases and 2 with github actions

**Comment by js6pak** [comment]
Hypixel (or cloudflare) started throwing 403 with `error code: 1020` for all requests containing `rewardclaim` in the useragent. Which probably means that is an "official" declaration that they are not okay with it?

**Comment by jkroepke** [comment]
idk, then they should do temp. bans. the mod list is sent to hypixel on first connection.
